chore(helm-docs): ✨ update error message for outdated README.md
* Simplified the error message for outdated `README.md` in the GitHub Actions workflow.
* Removed redundant step that exited with an error if the README was outdated.

Signed-off-by: Akshay Iyyadurai Balasundaram <akshay.iyyadurai.balasundaram@sap.com>

diff --git a/.github/workflows/helm-docs.yaml b/.github/workflows/helm-docs.yaml
--- a/.github/workflows/helm-docs.yaml
+++ b/.github/workflows/helm-docs.yaml
@@ -38,8 +38,5 @@ jobs:
       - name: Display README.md error
         if: steps.generate-readme.outputs.outdated == 'true'
         run: |
-          echo "::error file=charts/kubernetes-operations/README.md::README.md is outdated. Please run 'make generate-readme' and update the PR."
-
-      - name: Fail if README is outdated
-        if: steps.generate-readme.outputs.outdated == 'true'
-        run: exit 1
+          echo "::error file=README.md::README.md is outdated. Please run 'make generate-readme' and update the PR."
+          exit 1
